package lk.jiat.smarttrade.dto;

public class PayHereDTO {
    /* make dto for the required PayHere parameters
    Required Parameters
    merchant_id - PayHere Merchant ID
    return_url - URL to redirect users when success
    cancel_url - URL to redirect users when cancelled
    notify_url - URL to call back the status of the payment (Needs to be a URL accessible on a public IP/domain)
    first_name - Customer’s First Name
    last_name - Customer’s Last Name
    email - Customer’s Email
    phone - Customer’s Phone No
    address - Customer’s Address Line1 + Line2
    city - Customer’s City
    country - Customer’s Country
    order_id - Order ID generated by the merchant
    items - Item title or Order/Invoice number
    currency - Currency Code (LKR/USD)
    amount - Total Payment Amount
    hash - Generated hash value as mentioned below (*Required from 2023-01-16)
     */
    private boolean sandbox;
    private String merchantId;
    private String returnURL;
    private String cancelURL;
    private String notifyURL;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String address;
    private String city;
    private String country;
    private String orderId;
    private String items;
    private String currency;
    private String amount;
    private String hash;

    public boolean isSandbox() {
        return sandbox;
    }

    public void setSandbox(boolean sandbox) {
        this.sandbox = sandbox;
    }

    public String getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public String getReturnURL() {
        return returnURL;
    }

    public void setReturnURL(String returnURL) {
        this.returnURL = returnURL;
    }

    public String getCancelURL() {
        return cancelURL;
    }

    public void setCancelURL(String cancelURL) {
        this.cancelURL = cancelURL;
    }

    public String getNotifyURL() {
        return notifyURL;
    }

    public void setNotifyURL(String notifyURL) {
        this.notifyURL = notifyURL;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getItems() {
        return items;
    }

    public void setItems(String items) {
        this.items = items;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }
}
